improve logging for failed delivery. Treat all exceptions as connection failures
INFO - 10-04-2018T09:27:20,632 - co.kademi.server.stream.audit.KademiAuditService  - tx complete tx=2106532209 updates=1 creates=0 loads=0
ERROR- 10-04-2018T09:27:20,649 - org.masukomi.aspirin.core.delivery.SendMessage  - Exception sending message with messageId: <144521924.498.1523309226351.JavaMail.root@worker1>
javax.mail.MessagingException: Exception reading response;
  nested exception is:
	java.net.SocketException: Connection reset
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2202)
	at com.sun.mail.smtp.SMTPTransport.issueCommand(SMTPTransport.java:2072)
	at com.sun.mail.smtp.SMTPTransport.issueSendCommand(SMTPTransport.java:2105)
	at com.sun.mail.smtp.SMTPTransport.finishData(SMTPTransport.java:1889)
	at com.sun.mail.smtp.SMTPTransport.sendMessage(SMTPTransport.java:1120)
	at org.masukomi.aspirin.core.delivery.SendMessage.handle(SendMessage.java:97)
	at org.masukomi.aspirin.core.delivery.DeliveryThread.deliver(DeliveryThread.java:197)
	at org.masukomi.aspirin.core.delivery.DeliveryThread.run(DeliveryThread.java:88)
Caused by: java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at com.sun.mail.util.TraceInputStream.read(TraceInputStream.java:124)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at com.sun.mail.util.LineInputStream.readLine(LineInputStream.java:89)
	at com.sun.mail.smtp.SMTPTransport.readServerResponse(SMTPTransport.java:2182)
	... 7 more